edition = "2024"
style_edition = "2024"
comment_width = 100
format_code_in_doc_comments = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"
imports_layout = "Vertical"
max_width = 100
newline_style = "Unix"
reorder_imports = true
struct_field_align_threshold = 10
use_field_init_shorthand = true
use_small_heuristics = "Max"
wrap_comments = true
