[workspace]
resolver = "3"
members = [
  "crates/*",
]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
anyhow = { version = "1" }
clap = { version = "4.5.53", features = ["derive"] }
futures = { version = "0.3" }
humantime = { version = "2" }
libc = { version = "0.2" }
num = { version = "0.4" }
quickcheck = { version = "1" }
quickcheck_macros = { version = "1" }
proc = { path= "crates/proc" }
reaper = { path = "crates/reaper" }
tempfile = { version = "3" }
testing = { path = "crates/testing" }
thiserror = { version = "1" }
tokio = { version = "1.48", features = ["full"] }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[workspace.lints.clippy]
# pedantic = "deny"

[workspace.lints.rust]
missing_docs = "deny"

[profile.dev.package.fenwicktree]
overflow-checks = false

[profile.release]
lto = true
codegen-units = 1
