[profile.release]
codegen-units = 1
lto = true

[workspace]
resolver = "3"
members = [
  "crates/ano",
  "crates/bit",
  "crates/bits",
]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.lints.rust]
missing_docs = "deny"

[workspace.lints.clippy]
# pedantic = "deny"

[workspace.dependencies]
num = { version = "0.4" }
