[profile.release]
codegen-units = 1
lto = true

[profile.dev.package.fenwicktree]
overflow-checks = false

[workspace]
resolver = "3"
members = [
  "crates/*",
]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.lints.rust]
missing_docs = "deny"

[workspace.lints.clippy]
# pedantic = "deny"

[workspace.dependencies]
libc = { version = "0.2" }
num = { version = "0.4" }
quickcheck_macros = { version = "1" }
quickcheck = { version = "1" }
tokio = { version = "1.48", features = ["full"] }
tracing = { version = "0.1" }
