[package]
name = "reaper"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
libc.workspace = true
tokio.workspace = true
tracing.workspace = true

[lints]
workspace = true
